seed: 42
device: 0

dest_train:
  batch_size: 512
  epochs: 200
  lr: 1.0e-4
  weight_decay: 1.0e-5
  clip: 0.1

dest_model:
  hidden_dim: 608
  num_layers: 1
  dropout: 0.6
  freeze_backbone: false

exp_root: "./xian/runs/destination_prediction"

cities:
  xa:
    train_des_set: "./data/xa/train_des_set"
    test_des_set: "./data/xa/test_des_set"
    num_segments: 4000

    input_len: 20
    train_min_len: 20
    train_max_len: 10000
    test_min_len: 20
    test_max_len: 10000
