seed: 0
device: 0

label_train:
  batch_size: 512
  epochs: 100
  lr: 5.0e-4
  weight_decay: 1.0e-5

label_model:
  hidden_dim: 608
  num_classes: 2
  num_layers: 2
  dropout: 0.4
  freeze_backbone: false

exp_root: "./beijing/runs/label_prediction"

cities:
  bj:
    train_pred_train_set: "./data/bj/label_pred_train_set"
    train_pred_train_set_false: "./data/bj/label_pred_train_set_false"
    num_segments: 16000
