seed: 42
device: 2

dest_train:
  batch_size: 128
  epochs: 200
  lr: 1.0e-4
  weight_decay: 1.0e-5
  clip: 0.1

dest_model:
  hidden_dim: 608
  num_layers: 2
  dropout: 0.8
  freeze_backbone: false

exp_root: "./chengdu/runs/destination_prediction"

cities:
  cd:
    train_des_set: "./data/cd/train_des_set"
    test_des_set: "./data/cd/test_des_set"
    num_segments: 3000

    input_len: 10
    train_min_len: 10
    train_max_len: 10000
    test_min_len: 20
    test_max_len: 10000
