seed: 42
device: 0

next_train:
  batch_size: 512
  epochs: 200
  lr: 5.0e-4
  weight_decay: 1.0e-5
  clip: 0.1

next_model:
  hidden_dim: 608
  num_layers: 3
  dropout: 0.8
  freeze_backbone: false

exp_root: "./chengdu/runs/next_location_prediction"

cities:
  cd:
    train_loc_set: "./data/cd/train_loc_set"
    test_loc_set: "./data/cd/test_loc_set"
    num_segments: 3000

    train_min_len: 4
    train_max_len: 10000
    test_min_len: 4
    test_max_len: 10000
